import Foundation

struct Country: Identifiable, Hashable {
  let id: String
  let name: String
  let dialCode: String
  let flag: String
}

extension Country {
  static let `default` = us
  static let us = Country(id: "US", name: "United States", dialCode: "+1", flag: "🇺🇸")

  static let all: [Country] = [
    Country(id: "AF", name: "Afghanistan", dialCode: "+93", flag: "🇦🇫"),
    Country(id: "AL", name: "Albania", dialCode: "+355", flag: "🇦🇱"),
    Country(id: "DZ", name: "Algeria", dialCode: "+213", flag: "🇩🇿"),
    Country(id: "AS", name: "American Samoa", dialCode: "+1", flag: "🇦🇸"),
    Country(id: "AD", name: "Andorra", dialCode: "+376", flag: "🇦🇩"),
    Country(id: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴"),
    Country(id: "AI", name: "Anguilla", dialCode: "+1", flag: "🇦🇮"),
    Country(id: "AG", name: "Antigua and Barbuda", dialCode: "+1", flag: "🇦🇬"),
    Country(id: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷"),
    Country(id: "AM", name: "Armenia", dialCode: "+374", flag: "🇦🇲"),
    Country(id: "AW", name: "Aruba", dialCode: "+297", flag: "🇦🇼"),
    Country(id: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺"),
    Country(id: "AT", name: "Austria", dialCode: "+43", flag: "🇦🇹"),
    Country(id: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "🇦🇿"),
    Country(id: "BS", name: "Bahamas", dialCode: "+1", flag: "🇧🇸"),
    Country(id: "BH", name: "Bahrain", dialCode: "+973", flag: "🇧🇭"),
    Country(id: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩"),
    Country(id: "BB", name: "Barbados", dialCode: "+1", flag: "🇧🇧"),
    Country(id: "BY", name: "Belarus", dialCode: "+375", flag: "🇧🇾"),
    Country(id: "BE", name: "Belgium", dialCode: "+32", flag: "🇧🇪"),
    Country(id: "BZ", name: "Belize", dialCode: "+501", flag: "🇧🇿"),
    Country(id: "BJ", name: "Benin", dialCode: "+229", flag: "🇧🇯"),
    Country(id: "BM", name: "Bermuda", dialCode: "+1", flag: "🇧🇲"),
    Country(id: "BT", name: "Bhutan", dialCode: "+975", flag: "🇧🇹"),
    Country(id: "BO", name: "Bolivia", dialCode: "+591", flag: "🇧🇴"),
    Country(id: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "🇧🇦"),
    Country(id: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼"),
    Country(id: "BR", name: "Brazil", dialCode: "+55", flag: "🇧🇷"),
    Country(id: "IO", name: "British Indian Ocean Territory", dialCode: "+246", flag: "🇮🇴"),
    Country(id: "VG", name: "British Virgin Islands", dialCode: "+1", flag: "🇻🇬"),
    Country(id: "BN", name: "Brunei", dialCode: "+673", flag: "🇧🇳"),
    Country(id: "BG", name: "Bulgaria", dialCode: "+359", flag: "🇧🇬"),
    Country(id: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫"),
    Country(id: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮"),
    Country(id: "KH", name: "Cambodia", dialCode: "+855", flag: "🇰🇭"),
    Country(id: "CM", name: "Cameroon", dialCode: "+237", flag: "🇨🇲"),
    Country(id: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦"),
    Country(id: "CV", name: "Cape Verde", dialCode: "+238", flag: "🇨🇻"),
    Country(id: "KY", name: "Cayman Islands", dialCode: "+1", flag: "🇰🇾"),
    Country(id: "CF", name: "Central African Republic", dialCode: "+236", flag: "🇨🇫"),
    Country(id: "TD", name: "Chad", dialCode: "+235", flag: "🇹🇩"),
    Country(id: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱"),
    Country(id: "CN", name: "China", dialCode: "+86", flag: "🇨🇳"),
    Country(id: "CX", name: "Christmas Island", dialCode: "+61", flag: "🇨🇽"),
    Country(id: "CC", name: "Cocos Islands", dialCode: "+61", flag: "🇨🇨"),
    Country(id: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴"),
    Country(id: "KM", name: "Comoros", dialCode: "+269", flag: "🇰🇲"),
    Country(id: "CK", name: "Cook Islands", dialCode: "+682", flag: "🇨🇰"),
    Country(id: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷"),
    Country(id: "HR", name: "Croatia", dialCode: "+385", flag: "🇭🇷"),
    Country(id: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺"),
    Country(id: "CW", name: "Curaçao", dialCode: "+599", flag: "🇨🇼"),
    Country(id: "CY", name: "Cyprus", dialCode: "+357", flag: "🇨🇾"),
    Country(id: "CZ", name: "Czechia", dialCode: "+420", flag: "🇨🇿"),
    Country(id: "CD", name: "DR Congo", dialCode: "+243", flag: "🇨🇩"),
    Country(id: "DK", name: "Denmark", dialCode: "+45", flag: "🇩🇰"),
    Country(id: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯"),
    Country(id: "DM", name: "Dominica", dialCode: "+1", flag: "🇩🇲"),
    Country(id: "DO", name: "Dominican Republic", dialCode: "+1", flag: "🇩🇴"),
    Country(id: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨"),
    Country(id: "EG", name: "Egypt", dialCode: "+20", flag: "🇪🇬"),
    Country(id: "SV", name: "El Salvador", dialCode: "+503", flag: "🇸🇻"),
    Country(id: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶"),
    Country(id: "ER", name: "Eritrea", dialCode: "+291", flag: "🇪🇷"),
    Country(id: "EE", name: "Estonia", dialCode: "+372", flag: "🇪🇪"),
    Country(id: "SZ", name: "Eswatini", dialCode: "+268", flag: "🇸🇿"),
    Country(id: "ET", name: "Ethiopia", dialCode: "+251", flag: "🇪🇹"),
    Country(id: "FK", name: "Falkland Islands", dialCode: "+500", flag: "🇫🇰"),
    Country(id: "FO", name: "Faroe Islands", dialCode: "+298", flag: "🇫🇴"),
    Country(id: "FJ", name: "Fiji", dialCode: "+679", flag: "🇫🇯"),
    Country(id: "FI", name: "Finland", dialCode: "+358", flag: "🇫🇮"),
    Country(id: "FR", name: "France", dialCode: "+33", flag: "🇫🇷"),
    Country(id: "GF", name: "French Guiana", dialCode: "+594", flag: "🇬🇫"),
    Country(id: "PF", name: "French Polynesia", dialCode: "+689", flag: "🇵🇫"),
    Country(id: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦"),
    Country(id: "GM", name: "Gambia", dialCode: "+220", flag: "🇬🇲"),
    Country(id: "GE", name: "Georgia", dialCode: "+995", flag: "🇬🇪"),
    Country(id: "DE", name: "Germany", dialCode: "+49", flag: "🇩🇪"),
    Country(id: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭"),
    Country(id: "GI", name: "Gibraltar", dialCode: "+350", flag: "🇬🇮"),
    Country(id: "GR", name: "Greece", dialCode: "+30", flag: "🇬🇷"),
    Country(id: "GL", name: "Greenland", dialCode: "+299", flag: "🇬🇱"),
    Country(id: "GD", name: "Grenada", dialCode: "+1", flag: "🇬🇩"),
    Country(id: "GP", name: "Guadeloupe", dialCode: "+590", flag: "🇬🇵"),
    Country(id: "GU", name: "Guam", dialCode: "+1", flag: "🇬🇺"),
    Country(id: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹"),
    Country(id: "GG", name: "Guernsey", dialCode: "+44", flag: "🇬🇬"),
    Country(id: "GN", name: "Guinea", dialCode: "+224", flag: "🇬🇳"),
    Country(id: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼"),
    Country(id: "GY", name: "Guyana", dialCode: "+592", flag: "🇬🇾"),
    Country(id: "HT", name: "Haiti", dialCode: "+509", flag: "🇭🇹"),
    Country(id: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳"),
    Country(id: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰"),
    Country(id: "HU", name: "Hungary", dialCode: "+36", flag: "🇭🇺"),
    Country(id: "IS", name: "Iceland", dialCode: "+354", flag: "🇮🇸"),
    Country(id: "IN", name: "India", dialCode: "+91", flag: "🇮🇳"),
    Country(id: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩"),
    Country(id: "IR", name: "Iran", dialCode: "+98", flag: "🇮🇷"),
    Country(id: "IQ", name: "Iraq", dialCode: "+964", flag: "🇮🇶"),
    Country(id: "IE", name: "Ireland", dialCode: "+353", flag: "🇮🇪"),
    Country(id: "IM", name: "Isle of Man", dialCode: "+44", flag: "🇮🇲"),
    Country(id: "IL", name: "Israel", dialCode: "+972", flag: "🇮🇱"),
    Country(id: "IT", name: "Italy", dialCode: "+39", flag: "🇮🇹"),
    Country(id: "CI", name: "Ivory Coast", dialCode: "+225", flag: "🇨🇮"),
    Country(id: "JM", name: "Jamaica", dialCode: "+1", flag: "🇯🇲"),
    Country(id: "JP", name: "Japan", dialCode: "+81", flag: "🇯🇵"),
    Country(id: "JE", name: "Jersey", dialCode: "+44", flag: "🇯🇪"),
    Country(id: "JO", name: "Jordan", dialCode: "+962", flag: "🇯🇴"),
    Country(id: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿"),
    Country(id: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪"),
    Country(id: "KI", name: "Kiribati", dialCode: "+686", flag: "🇰🇮"),
    Country(id: "XK", name: "Kosovo", dialCode: "+383", flag: "🇽🇰"),
    Country(id: "KW", name: "Kuwait", dialCode: "+965", flag: "🇰🇼"),
    Country(id: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬"),
    Country(id: "LA", name: "Laos", dialCode: "+856", flag: "🇱🇦"),
    Country(id: "LV", name: "Latvia", dialCode: "+371", flag: "🇱🇻"),
    Country(id: "LB", name: "Lebanon", dialCode: "+961", flag: "🇱🇧"),
    Country(id: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸"),
    Country(id: "LR", name: "Liberia", dialCode: "+231", flag: "🇱🇷"),
    Country(id: "LY", name: "Libya", dialCode: "+218", flag: "🇱🇾"),
    Country(id: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮"),
    Country(id: "LT", name: "Lithuania", dialCode: "+370", flag: "🇱🇹"),
    Country(id: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺"),
    Country(id: "MO", name: "Macao", dialCode: "+853", flag: "🇲🇴"),
    Country(id: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬"),
    Country(id: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼"),
    Country(id: "MY", name: "Malaysia", dialCode: "+60", flag: "🇲🇾"),
    Country(id: "MV", name: "Maldives", dialCode: "+960", flag: "🇲🇻"),
    Country(id: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱"),
    Country(id: "MT", name: "Malta", dialCode: "+356", flag: "🇲🇹"),
    Country(id: "MH", name: "Marshall Islands", dialCode: "+692", flag: "🇲🇭"),
    Country(id: "MQ", name: "Martinique", dialCode: "+596", flag: "🇲🇶"),
    Country(id: "MR", name: "Mauritania", dialCode: "+222", flag: "🇲🇷"),
    Country(id: "MU", name: "Mauritius", dialCode: "+230", flag: "🇲🇺"),
    Country(id: "YT", name: "Mayotte", dialCode: "+262", flag: "🇾🇹"),
    Country(id: "MX", name: "Mexico", dialCode: "+52", flag: "🇲🇽"),
    Country(id: "FM", name: "Micronesia", dialCode: "+691", flag: "🇫🇲"),
    Country(id: "MD", name: "Moldova", dialCode: "+373", flag: "🇲🇩"),
    Country(id: "MC", name: "Monaco", dialCode: "+377", flag: "🇲🇨"),
    Country(id: "MN", name: "Mongolia", dialCode: "+976", flag: "🇲🇳"),
    Country(id: "ME", name: "Montenegro", dialCode: "+382", flag: "🇲🇪"),
    Country(id: "MS", name: "Montserrat", dialCode: "+1", flag: "🇲🇸"),
    Country(id: "MA", name: "Morocco", dialCode: "+212", flag: "🇲🇦"),
    Country(id: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿"),
    Country(id: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲"),
    Country(id: "NA", name: "Namibia", dialCode: "+264", flag: "🇳🇦"),
    Country(id: "NR", name: "Nauru", dialCode: "+674", flag: "🇳🇷"),
    Country(id: "NP", name: "Nepal", dialCode: "+977", flag: "🇳🇵"),
    Country(id: "NL", name: "Netherlands", dialCode: "+31", flag: "🇳🇱"),
    Country(id: "NC", name: "New Caledonia", dialCode: "+687", flag: "🇳🇨"),
    Country(id: "NZ", name: "New Zealand", dialCode: "+64", flag: "🇳🇿"),
    Country(id: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮"),
    Country(id: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪"),
    Country(id: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬"),
    Country(id: "NU", name: "Niue", dialCode: "+683", flag: "🇳🇺"),
    Country(id: "NF", name: "Norfolk Island", dialCode: "+672", flag: "🇳🇫"),
    Country(id: "KP", name: "North Korea", dialCode: "+850", flag: "🇰🇵"),
    Country(id: "MK", name: "North Macedonia", dialCode: "+389", flag: "🇲🇰"),
    Country(id: "MP", name: "Northern Mariana Islands", dialCode: "+1", flag: "🇲🇵"),
    Country(id: "NO", name: "Norway", dialCode: "+47", flag: "🇳🇴"),
    Country(id: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲"),
    Country(id: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰"),
    Country(id: "PW", name: "Palau", dialCode: "+680", flag: "🇵🇼"),
    Country(id: "PS", name: "Palestine", dialCode: "+970", flag: "🇵🇸"),
    Country(id: "PA", name: "Panama", dialCode: "+507", flag: "🇵🇦"),
    Country(id: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬"),
    Country(id: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾"),
    Country(id: "PE", name: "Peru", dialCode: "+51", flag: "🇵🇪"),
    Country(id: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭"),
    Country(id: "PL", name: "Poland", dialCode: "+48", flag: "🇵🇱"),
    Country(id: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹"),
    Country(id: "PR", name: "Puerto Rico", dialCode: "+1", flag: "🇵🇷"),
    Country(id: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦"),
    Country(id: "CG", name: "Republic of the Congo", dialCode: "+242", flag: "🇨🇬"),
    Country(id: "RE", name: "Réunion", dialCode: "+262", flag: "🇷🇪"),
    Country(id: "RO", name: "Romania", dialCode: "+40", flag: "🇷🇴"),
    Country(id: "RU", name: "Russia", dialCode: "+7", flag: "🇷🇺"),
    Country(id: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼"),
    Country(id: "BL", name: "Saint Barthélemy", dialCode: "+590", flag: "🇧🇱"),
    Country(id: "SH", name: "Saint Helena", dialCode: "+290", flag: "🇸🇭"),
    Country(id: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", flag: "🇰🇳"),
    Country(id: "LC", name: "Saint Lucia", dialCode: "+1", flag: "🇱🇨"),
    Country(id: "MF", name: "Saint Martin", dialCode: "+590", flag: "🇲🇫"),
    Country(id: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", flag: "🇵🇲"),
    Country(id: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1", flag: "🇻🇨"),
    Country(id: "WS", name: "Samoa", dialCode: "+685", flag: "🇼🇸"),
    Country(id: "SM", name: "San Marino", dialCode: "+378", flag: "🇸🇲"),
    Country(id: "ST", name: "São Tomé and Príncipe", dialCode: "+239", flag: "🇸🇹"),
    Country(id: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦"),
    Country(id: "SN", name: "Senegal", dialCode: "+221", flag: "🇸🇳"),
    Country(id: "RS", name: "Serbia", dialCode: "+381", flag: "🇷🇸"),
    Country(id: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨"),
    Country(id: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱"),
    Country(id: "SG", name: "Singapore", dialCode: "+65", flag: "🇸🇬"),
    Country(id: "SX", name: "Sint Maarten", dialCode: "+1", flag: "🇸🇽"),
    Country(id: "SK", name: "Slovakia", dialCode: "+421", flag: "🇸🇰"),
    Country(id: "SI", name: "Slovenia", dialCode: "+386", flag: "🇸🇮"),
    Country(id: "SB", name: "Solomon Islands", dialCode: "+677", flag: "🇸🇧"),
    Country(id: "SO", name: "Somalia", dialCode: "+252", flag: "🇸🇴"),
    Country(id: "ZA", name: "South Africa", dialCode: "+27", flag: "🇿🇦"),
    Country(id: "KR", name: "South Korea", dialCode: "+82", flag: "🇰🇷"),
    Country(id: "SS", name: "South Sudan", dialCode: "+211", flag: "🇸🇸"),
    Country(id: "ES", name: "Spain", dialCode: "+34", flag: "🇪🇸"),
    Country(id: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰"),
    Country(id: "SD", name: "Sudan", dialCode: "+249", flag: "🇸🇩"),
    Country(id: "SR", name: "Suriname", dialCode: "+597", flag: "🇸🇷"),
    Country(id: "SE", name: "Sweden", dialCode: "+46", flag: "🇸🇪"),
    Country(id: "CH", name: "Switzerland", dialCode: "+41", flag: "🇨🇭"),
    Country(id: "SY", name: "Syria", dialCode: "+963", flag: "🇸🇾"),
    Country(id: "TW", name: "Taiwan", dialCode: "+886", flag: "🇹🇼"),
    Country(id: "TJ", name: "Tajikistan", dialCode: "+992", flag: "🇹🇯"),
    Country(id: "TZ", name: "Tanzania", dialCode: "+255", flag: "🇹🇿"),
    Country(id: "TH", name: "Thailand", dialCode: "+66", flag: "🇹🇭"),
    Country(id: "TL", name: "Timor-Leste", dialCode: "+670", flag: "🇹🇱"),
    Country(id: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬"),
    Country(id: "TK", name: "Tokelau", dialCode: "+690", flag: "🇹🇰"),
    Country(id: "TO", name: "Tonga", dialCode: "+676", flag: "🇹🇴"),
    Country(id: "TT", name: "Trinidad and Tobago", dialCode: "+1", flag: "🇹🇹"),
    Country(id: "TN", name: "Tunisia", dialCode: "+216", flag: "🇹🇳"),
    Country(id: "TR", name: "Turkey", dialCode: "+90", flag: "🇹🇷"),
    Country(id: "TM", name: "Turkmenistan", dialCode: "+993", flag: "🇹🇲"),
    Country(id: "TC", name: "Turks and Caicos Islands", dialCode: "+1", flag: "🇹🇨"),
    Country(id: "TV", name: "Tuvalu", dialCode: "+688", flag: "🇹🇻"),
    Country(id: "UG", name: "Uganda", dialCode: "+256", flag: "🇺🇬"),
    Country(id: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦"),
    Country(id: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪"),
    Country(id: "GB", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧"),
    us,
    Country(id: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾"),
    Country(id: "VI", name: "US Virgin Islands", dialCode: "+1", flag: "🇻🇮"),
    Country(id: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "🇺🇿"),
    Country(id: "VU", name: "Vanuatu", dialCode: "+678", flag: "🇻🇺"),
    Country(id: "VA", name: "Vatican City", dialCode: "+39", flag: "🇻🇦"),
    Country(id: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪"),
    Country(id: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳"),
    Country(id: "WF", name: "Wallis and Futuna", dialCode: "+681", flag: "🇼🇫"),
    Country(id: "EH", name: "Western Sahara", dialCode: "+212", flag: "🇪🇭"),
    Country(id: "YE", name: "Yemen", dialCode: "+967", flag: "🇾🇪"),
    Country(id: "ZM", name: "Zambia", dialCode: "+260", flag: "🇿🇲"),
    Country(id: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼"),
  ]
}
